### ISSUE TITLE
增加一键移除所有燃料箱的FuelTank属性

### ISSUE THREAD

**Issue by MOXMAKER** [Server-WX/SR2-Toolkit-for-Android#1]
我发现这个FuelTank属性删除后不会影响板材燃料罐的性能，形状是由Fuselage决定的，所以我猜可以删掉他节约性能
燃料罐的PartType是 partType="Fuselage1"，我觉得可以用这个检测燃料罐子然后删掉其中的<fueltank />瞎说的

**Comment by df7x** [comment]
该功能并未起到实际作用
